### ISSUE TITLE
missing license file

### ISSUE THREAD

**Issue by TheBestJohn** [ZachHofmeister/ShapePlane#2]
Hey there! Nifty project.

I pulled out the dropbox stuff because, as you had said, it wasn't used anymore.
I've also tested the latest GUI library on my fork and it seems to work.

Just wondering what the license you've attaches to this is. GPL, MIT, Proprietary?

**Comment by ZachHofmeister** [comment]
Hey John, I'm glad for your interest in my project! Sorry for taking such a long time to get back to you. Your changes look good, I merged them with the main branch. Also I never considered licensing, but GPL seems like it would be appropriate for this project. Thanks!

**Comment by TheBestJohn** [comment]
Hey no problem. Thanks for sharing it! It's great and seems like it would have been a lot of fun to program. I just wanted to confirm the licensing as I did see some serial number code and I didn't want to step on toes. In case you're wondering what I was using it for, I was exporting svgs and making gcode for a hacked 3d printer to plot out on post-it notes
